name: Container Image CI

on:
  push:
    branches:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract branch name
        id: vars
        run: echo "tag=${GITHUB_REF##refs/heads/}" >> "$GITHUB_OUTPUT"

      - name: Build the Docker image
        run: |
          docker build \
            --file docker/Dockerfile \
            --build-arg BUILD_VERSION=${{ steps.vars.outputs.tag }} \
            --tag ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag }} \
            .

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag }}
